var EventUtil={addHandler:function(element,type,handler){if(element.addEventListener)element.addEventListener(type,handler,false);else if(element.attachEvent)element.attachEvent("on"+type,handler);else element["on"+type]=null},removeHandler:function(element,type,handler){if(element.removeHandler)element.removeHandler(type,handler,false);else if(element.detachEvent)element.detachEvent("on"+type,handler);else element["on"+type]=null},getEvent:function(event){return event?event:window.event},getTarget:function(event){return event.target||
event.srcElement},preventDefault:function(event){if(event.preventDefault)event.preventDefault();else event.returnValue=false},stopPropagation:function(event){if(event.stopPropagation)event.stopPropagation();else event.cancelBubble=false}};function getByClass(clsName,parent){var oParent=parent?document.getElementById(parent):document,eles=[],elements=oParent.getElementsByTagName("*");for(var i=0,l=elements.length;i<l;i++)if(elements[i].className==clsName)eles.push(elements[i]);return eles}
window.onload=function(){drag();register();setInterval(countdown,1E3);waterfall("album","pin");var data={"data":["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg","9.jpg","10.jpg","11.jpg","12.jpg"]};window.onscroll=function(){while(checkscrollside()&&(document.documentElement.scrollTop||document.body.scrollTop)<400){var oParent=document.getElementById("album");for(var i=0;i<data.data.length;i++){var oPin=document.createElement("div");var oBox=document.createElement("div");var oImg=
document.createElement("img");oPin.className="pin";oBox.className="box";oParent.appendChild(oPin);oPin.appendChild(oBox);oBox.appendChild(oImg);oImg.src="images/"+data.data[i]}waterfall("album","pin")}};$(function(){$(window).scroll(function(){if($(window).scrollTop()>250)$("#backTop").fadeIn(500);else $("#backTop").fadeOut(300)});$("#backTop").click(function(){$("body, html").animate({scrollTop:0},1E3);return false})})};
function drag(){var oDog=document.getElementById("dog");oDog.onmousedown=fnDown}function fnDown(event){event=EventUtil.getEvent();var oDog=document.getElementById("dog"),disX=event.clientX-oDog.offsetLeft,disY=event.clientY-oDog.offsetTop;document.onmousemove=function(event){fnMove(event,disX,disY)};document.onmouseup=function(){document.onmousemove=null;document.onmouseup=null}}
function fnMove(e,posX,posY){var oDog=document.getElementById("dog"),l=e.clientX-posX,t=e.clientY-posY,winW=document.getElementById("backhome").offsetWidth,winH=document.getElementById("backhome").offsetHeight,maxW=winW-oDog.offsetWidth,maxH=winH-oDog.offsetHeight;if(l<0)l=0;else if(l>maxW)l=maxW;if(t<0)t=0;else if(t>maxH)t=maxH;oDog.style.left=l+"px";oDog.style.top=t+"px"}
function register(){var oName=document.getElementById("name");var count=document.getElementById("count");var psw=document.getElementById("psw");var psw2=document.getElementById("psw2");var email=document.getElementById("email");var form=document.getElementById("form");var name_msg=document.getElementsByClassName("name_msg")[0];var psw_msg=document.getElementsByClassName("psw_msg")[0];var psw2_msg=document.getElementsByClassName("psw2_msg")[0];var email_msg=document.getElementsByClassName("email_msg")[0];
var psw=document.getElementById("psw");var psw2=document.getElementById("psw2");var intensity=getByClass("intensity")[0].getElementsByTagName("span");var registerbtn=document.getElementById("submit");var oName_state=false;var email_state=false;var psw_state=false;var psw2_state=false;var name_length=0;oName.onfocus=function(){name_msg.style.display="inline-block"};oName.onkeyup=function(){count.style.visibility="visible";name_length=getLength(this.value);count.innerHTML=name_length+"\u4e2a\u5b57\u7b26";
if(name_length==0)count.style.visibility="hidden"};oName.onblur=function(){var re=/[^\w\u4e00-\u9fa5]/g;if(re.test(this.value)){name_msg.innerHTML="<i class='fa fa-close'>\u542b\u6709\u975e\u6cd5\u5b57\u7b26</i>";oName_state=false}else if(this.value==""){name_msg.innerHTML="<i class='fa fa-close'>\u4e0d\u80fd\u4e3a\u7a7a</i>";oName_state=false}else if(name_length>25){name_msg.innerHTML="<i class='fa fa-close'>\u4e0d\u80fd\u8d85\u51fa25\u4e2a\u5b57\u7b26</i>";oName_state=false}else if(name_length<
6){name_msg.innerHTML="<i class='fa fa-close'>\u4e0d\u80fd\u5c11\u4e8e6\u4e2a\u5b57\u7b26</i>";oName_state=false}else{name_msg.innerHTML="<i class='fa fa-check-square'>OK!</i>";oName_state=true}checkform()};psw.onfocus=function(){psw_msg.style.display="inline-block";psw_msg.innerHTML="<i class='fa fa-lightbulb-o'>6-16\u4e2a\u5b57\u7b26\uff0c\u4e0d\u80fd\u5355\u72ec\u4f7f\u7528\u5b57\u6bcd\u3001\u6570\u5b57\u6216\u7b26\u53f7</i>"};psw.onkeyup=function(){if(this.value.length>5){intensity[1].className=
"active";psw2.removeAttribute("disabled");psw2_msg.style.display="inline-block"}else{intensity[1].className="";psw2.setAttribute("disabled","");psw2_msg.style.display="none"}if(this.value.length>10){intensity[2].className="active";psw2.removeAttribute("disabled");psw2_msg.style.display="inline-block"}else intensity[2].className=""};psw.onblur=function(){var m=findStr(psw.value,psw.value[0]);var re_n=/[^\d]/g;var re_t=/[^a-zA-Z]/g;if(this.value==""){psw_msg.innerHTML="<i class='fa fa-close'>\u4e0d\u80fd\u4e3a\u7a7a</i>";
psw_state=false}else if(m==this.value.length){psw_msg.innerHTML="<i class='fa fa-close'>\u4e0d\u80fd\u4e3a\u76f8\u540c\u5b57\u7b26</i>";psw_state=false}else if(this.value.length<6||this.value.legth>16){psw_msg.innerHTML="<i class='fa fa-close'>\u957f\u5ea6\u5e94\u4e3a6-16\u4e2a\u5b57\u7b26</i>";psw_state=false}else if(!re_n.test(this.value)){psw_msg.innerHTML="<i class='fa fa-close'>\u4e0d\u80fd\u5168\u90e8\u4e3a\u6570\u5b57</i>";psw_state=false}else if(!re_t.test(this.value)){psw_msg.innerHTML="<i class='fa fa-close'>\u4e0d\u80fd\u5168\u90e8\u4e3a\u5b57\u6bcd</i>";
psw_state=false}else{psw_msg.innerHTML="<i class='fa fa-check-square'>OK!</i>";psw_state=true}checkform()};psw2.onkeyup=function(){if(psw2.value!=psw.value){psw2_msg.innerHTML="<i class='fa fa-close'>\u4e24\u6b21\u8f93\u5165\u4e0d\u4e00\u81f4</i>";psw2_state=false}else{psw2_msg.innerHTML="<i class='fa fa-check-square'>OK!</i>";psw2_state=true}checkform()};email.onfocus=function(){email_msg.style.display="inline-block"};email.onblur=function(){var re_e=/^[\w_\-\.]+@[\w]+\.([\w]{2,4})$/g;if(!re_e.test(this.value)){email_msg.innerHTML=
"<i class='fa fa-close'>\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u90ae\u7bb1\u683c\u5f0f</i>";email_state=false}else{email_msg.innerHTML="<i class='fa fa-check-square'>OK!</i>";email_state=true}checkform()};function checkform(){if(oName_state&&oName_state&&psw_state&&psw2_state){registerbtn.removeAttribute("disabled");$("#submit").addClass("readySubmit")}else{registerbtn.setAttribute("disabled","");$("#submit").removeClass("readySubmit")}}EventUtil.addHandler(form,"submit",function(event){event=EventUtil.getEvent(event);
var target=EventUtil.getTarget(event);registerbtn.setAttribute("disabled","");$("#submit").removeClass("readySubmit");$.ajax({type:"post",url:"api/register",data:$("#form").serialize(),success:function(){alert("\u6ce8\u518c\u6210\u529f")},error:function(){alert("\u6ce8\u518c\u5931\u8d25")}})})}function getLength(str){return str.replace(/[^\x00-xff]/g,"xx").length}function findStr(str,n){var temp=0;for(var i=0;i<str.length;i++)if(str.charAt(i)==n)temp++;return temp}
function countdown(){var deadline=new Date(2016,9,11);var date=new Date;var endtime=parseInt((deadline-date)/1E3);var days=parseInt(endtime/(60*60*24));var hours=parseInt(endtime/(60*60)%24);var minutes=parseInt(endtime/60%60);var seconds=parseInt(endtime%60);var timer=document.getElementById("countdown");timer.innerHTML="\u8ddd\u79bb\u6211\u4e0b\u4e00\u4e2a\u5341\u516b\u5c81\u751f\u65e5\u8fd8\u6709\uff1a"+days+"\u5929"+hours+"\u5c0f\u65f6"+minutes+"\u5206\u949f"+seconds+"\u79d2"}
function waterfall(parent,pin){var oParent=document.getElementById(parent);var aPin=getByClass(pin,parent);var iPinW=aPin[0].offsetWidth;var num=Math.floor(document.documentElement.clientWidth/iPinW);oParent.style.cssText="position:relative;width:"+iPinW*num+"px;margin:0 auto;";var pinHArr=[];for(var i=0;i<aPin.length;i++)if(i<num)pinHArr.push(aPin[i].offsetHeight);else{var minH=Math.min.apply(null,pinHArr);var minHIndex=pinHArr.indexOf(minH);aPin[i].style.position="absolute";aPin[i].style.left=aPin[minHIndex].offsetLeft+
"px";aPin[i].style.top=minH+"px";pinHArr[minHIndex]+=aPin[i].offsetHeight}oParent.style.height=Math.max.apply(null,pinHArr)+"px"}function checkscrollside(){var oParent=document.getElementById("main");var aPin=getByClass("pin",oParent);var lastPinH=aPin[aPin.length-1].offsetTop+Math.floor(aPin[aPin.length-1].offsetHeight/2);var scrollTop=document.documentElement.scrollTop||document.body.scrollTop;var documentH=document.documentElement.clientHeight;return lastPinH<scrollTop+documentH?true:false};